GET http://localhost:4100/api/subscribers

###

GET http://localhost:4100/api/subscribers/5d1639f9d4099a17df2a7d61

###

POST http://localhost:4100/api/subscribers
Content-Type: application/json

{
  "name": "Lee Laing",
  "subscribedToChannel": "Battle for my Heart Channel"
}

###

PATCH http://localhost:4100/api/subscribers/5d166abd4d47d020b3b3939b
Content-Type: application/json

{
  "name": "Lee Charles Laing",
  "subscribedToChannel": "Battle for my Heart Youtube Channel"
}

###

DELETE http://localhost:4100/api/subscribers/5d166ac94d47d020b3b3939c

