GET http://localhost:4100/api/subscribers

###

GET http://localhost:4100/api/subscribers/5d1674794e40da22b598a87a

###

POST http://localhost:4100/api/subscribers
Content-Type: application/json

{
  "name": "Travis Charles Gentry",
  "subscribedToChannel": "Travis Gentry's Channel"
}

###

PATCH http://localhost:4100/api/subscribers/5d1674794e40da22b598a87a
Content-Type: application/json

{
  "name": "Travis Charles Gentry",
  "subscribedToChannel": "Battle for my Heart Youtube Channel"
}

###

DELETE http://localhost:4100/api/subscribers/5d1674794e40da22b598a87a

